# Data Cleaning

First we imported the data using pandas. We noticed that the data is missing headers so we added labels for each column.

In [214]:
import pandas as pd
import numpy as np

numOfHeaders = 29

#set the labels for the features
headers = ["feature "+str(i) for i in range(1,numOfHeaders)]

# mark the first column to be the target
headers = ["output"] + headers

#import the data and set the columns' headers to the labels
data = pd.read_csv("Downloads/HIGGS_train.csv",names = headers, low_memory=False)
data

,output,feature 1,feature 2,feature 3,feature 4,feature 5,feature 6,feature 7,feature 8,feature 9,...,feature 19,feature 20,feature 21,feature 22,feature 23,feature 24,feature 25,feature 26,feature 27,feature 28
0,1.0,0.869,-0.635,0.226,0.327,-0.690,0.754,-0.249,-1.09E+00,0.00,...,-0.0105,-0.045800,3.10E+00,1.350,0.980,0.978,0.920,0.722,0.989,0.877
1,1.0,0.908,0.329,0.359,1.500,-0.313,1.100,-0.558,-1.59E+00,2.17,...,-1.1400,-0.000819,0.00E+00,0.302,0.833,0.986,0.978,0.780,0.992,0.798
2,1.0,0.799,1.470,-1.640,0.454,0.426,1.100,1.280,1.38E+00,0.00,...,1.1300,0.900000,0.00E+00,0.910,1.110,0.986,0.951,0.803,0.866,0.780
3,0.0,1.340,-0.877,0.936,1.990,0.882,1.790,-1.650,-9.42E-01,0.00,...,-0.6780,-1.360000,0.00E+00,0.947,1.030,0.999,0.728,0.869,1.030,0.958
4,1.0,1.110,0.321,1.520,0.883,-1.210,0.681,-1.070,-9.22E-01,0.00,...,-0.3740,0.113000,0.00E+00,0.756,1.360,0.987,0.838,1.130,0.872,0.808
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,0.0,0.680,0.223,-0.757,0.418,-0.323,0.471,-0.394,1.03E-01,0.00,...,-2.4600,1.460000,0.00E+00,0.823,1.040,0.985,0.868,0.258,0.776,0.712
599996,1.0,1.610,-1.620,0.212,0.716,-0.906,0.553,-0.908,-1.56E+00,2.17,...,0.5380,-0.490000,3.10E+00,0.810,0.643,1.260,1.020,0.626,0.773,0.701
599997,1.0,1.070,0.364,0.344,0.617,-1.430,0.675,0.159,7.89E-02,0.00,...,0.9780,1.150000,3.10E+00,0.973,0.974,1.130,0.969,0.852,0.908,0.789
599998,1.0,1.180,-0.173,-1.460,0.735,-0.753,1.020,-0.838,1.23E+00,0.00,...,0.1070,0.622000,0.00E+00,0.812,1.240,0.986,0.694,0.745,0.741,0.728
599999,0.0,0.771,-0.133,-1.020,1.790,-1.650,0.779,0.487,1.90E-01,2.17,...,-0.3140,0.667000,0.00E+00,0.829,0.839,0.984,1.340,0.510,1.040,0.905

We noticed that there are some duplicated rows that we dropped down.

In [215]:
numOfDuplicatedRows = len(np.where(data.duplicated() == True)[0])
print("The number of duplicated rows = ",numOfDuplicatedRows)

data = data.drop_duplicates()
data

The number of duplicated rows =  802

,output,feature 1,feature 2,feature 3,feature 4,feature 5,feature 6,feature 7,feature 8,feature 9,...,feature 19,feature 20,feature 21,feature 22,feature 23,feature 24,feature 25,feature 26,feature 27,feature 28
0,1.0,0.869,-0.635,0.226,0.327,-0.690,0.754,-0.249,-1.09E+00,0.00,...,-0.0105,-0.045800,3.10E+00,1.350,0.980,0.978,0.920,0.722,0.989,0.877
1,1.0,0.908,0.329,0.359,1.500,-0.313,1.100,-0.558,-1.59E+00,2.17,...,-1.1400,-0.000819,0.00E+00,0.302,0.833,0.986,0.978,0.780,0.992,0.798
2,1.0,0.799,1.470,-1.640,0.454,0.426,1.100,1.280,1.38E+00,0.00,...,1.1300,0.900000,0.00E+00,0.910,1.110,0.986,0.951,0.803,0.866,0.780
3,0.0,1.340,-0.877,0.936,1.990,0.882,1.790,-1.650,-9.42E-01,0.00,...,-0.6780,-1.360000,0.00E+00,0.947,1.030,0.999,0.728,0.869,1.030,0.958
4,1.0,1.110,0.321,1.520,0.883,-1.210,0.681,-1.070,-9.22E-01,0.00,...,-0.3740,0.113000,0.00E+00,0.756,1.360,0.987,0.838,1.130,0.872,0.808
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,0.0,0.680,0.223,-0.757,0.418,-0.323,0.471,-0.394,1.03E-01,0.00,...,-2.4600,1.460000,0.00E+00,0.823,1.040,0.985,0.868,0.258,0.776,0.712
599996,1.0,1.610,-1.620,0.212,0.716,-0.906,0.553,-0.908,-1.56E+00,2.17,...,0.5380,-0.490000,3.10E+00,0.810,0.643,1.260,1.020,0.626,0.773,0.701
599997,1.0,1.070,0.364,0.344,0.617,-1.430,0.675,0.159,7.89E-02,0.00,...,0.9780,1.150000,3.10E+00,0.973,0.974,1.130,0.969,0.852,0.908,0.789
599998,1.0,1.180,-0.173,-1.460,0.735,-0.753,1.020,-0.838,1.23E+00,0.00,...,0.1070,0.622000,0.00E+00,0.812,1.240,0.986,0.694,0.745,0.741,0.728
599999,0.0,0.771,-0.133,-1.020,1.790,-1.650,0.779,0.487,1.90E-01,2.17,...,-0.3140,0.667000,0.00E+00,0.829,0.839,0.984,1.340,0.510,1.040,0.905

We searched for rows with missing data, and we got their indices and dropped them accordingly.

In [216]:
print("The number of rows that have null values is : ", len(np.where(data.isna().any(axis=1) == True)[0]))
#get the row with the missing data
rows = data[data.isna().any(axis=1)]
#get the index of that row and drop it
data = data.drop(rows.index,axis=0)
data

The number of rows that have null values is :  1

,output,feature 1,feature 2,feature 3,feature 4,feature 5,feature 6,feature 7,feature 8,feature 9,...,feature 19,feature 20,feature 21,feature 22,feature 23,feature 24,feature 25,feature 26,feature 27,feature 28
0,1.0,0.869,-0.635,0.226,0.327,-0.690,0.754,-0.249,-1.09E+00,0.00,...,-0.0105,-0.045800,3.10E+00,1.350,0.980,0.978,0.920,0.722,0.989,0.877
1,1.0,0.908,0.329,0.359,1.500,-0.313,1.100,-0.558,-1.59E+00,2.17,...,-1.1400,-0.000819,0.00E+00,0.302,0.833,0.986,0.978,0.780,0.992,0.798
2,1.0,0.799,1.470,-1.640,0.454,0.426,1.100,1.280,1.38E+00,0.00,...,1.1300,0.900000,0.00E+00,0.910,1.110,0.986,0.951,0.803,0.866,0.780
3,0.0,1.340,-0.877,0.936,1.990,0.882,1.790,-1.650,-9.42E-01,0.00,...,-0.6780,-1.360000,0.00E+00,0.947,1.030,0.999,0.728,0.869,1.030,0.958
4,1.0,1.110,0.321,1.520,0.883,-1.210,0.681,-1.070,-9.22E-01,0.00,...,-0.3740,0.113000,0.00E+00,0.756,1.360,0.987,0.838,1.130,0.872,0.808
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,0.0,0.680,0.223,-0.757,0.418,-0.323,0.471,-0.394,1.03E-01,0.00,...,-2.4600,1.460000,0.00E+00,0.823,1.040,0.985,0.868,0.258,0.776,0.712
599996,1.0,1.610,-1.620,0.212,0.716,-0.906,0.553,-0.908,-1.56E+00,2.17,...,0.5380,-0.490000,3.10E+00,0.810,0.643,1.260,1.020,0.626,0.773,0.701
599997,1.0,1.070,0.364,0.344,0.617,-1.430,0.675,0.159,7.89E-02,0.00,...,0.9780,1.150000,3.10E+00,0.973,0.974,1.130,0.969,0.852,0.908,0.789
599998,1.0,1.180,-0.173,-1.460,0.735,-0.753,1.020,-0.838,1.23E+00,0.00,...,0.1070,0.622000,0.00E+00,0.812,1.240,0.986,0.694,0.745,0.741,0.728
599999,0.0,0.771,-0.133,-1.020,1.790,-1.650,0.779,0.487,1.90E-01,2.17,...,-0.3140,0.667000,0.00E+00,0.829,0.839,0.984,1.340,0.510,1.040,0.905

We noticed that the data is not of the same type. We got the indices of the columns and the rows where the data is of type string. we looped over the cells with string data and converted them to float if applicable. if not, we replaced them with the mode of the column.

In [230]:
print("Is the data of the same type?",data.dtypes.nunique() == 1)
#get the indices of the columns that have non float values 
cols = np.where(data.dtypes != "float64")
#get the headers of those rows
cols = np.array([headers[i] for i in cols[0]])
#create a copy of the data
copyOfData = data
#convert everything to numeric type, if a data cell is non numeric, it will be converted to nan
copyOfData = copyOfData.apply(pd.to_numeric,errors='coerce')
#indices of the rows that contains non numeric values 
indices = np.where(copyOfData.isna().any(axis = 1))[0]

#loop over the rows
for row in indices:
    #loop over the elements of the row
    for col in cols:
        #get the element at that row at that col
        num = data.iloc[row][col]
        try: 
            #if applicable, get the numeric value of the string
            data = data.replace({col:{num:float(num.strip('"'))}})
        except:
            #replace the field with the mode
            data = data.replace({col:{num:data[col].mode()[0]}}) 
data

Is the data of the same type? False

,output,feature 1,feature 2,feature 3,feature 4,feature 5,feature 6,feature 7,feature 8,feature 9,...,feature 19,feature 20,feature 21,feature 22,feature 23,feature 24,feature 25,feature 26,feature 27,feature 28
0,1.0,0.869,-0.635,0.226,0.327,-0.690,0.754,-0.249,-1.09E+00,0.00,...,-0.0105,-0.045800,3.10E+00,1.350,0.980,0.978,0.920,0.722,0.989,0.877
1,1.0,0.908,0.329,0.359,1.500,-0.313,1.100,-0.558,-1.59E+00,2.17,...,-1.1400,-0.000819,0.0,0.302,0.833,0.986,0.978,0.780,0.992,0.798
2,1.0,0.799,1.470,-1.640,0.454,0.426,1.100,1.280,1.38E+00,0.00,...,1.1300,0.900000,0.0,0.910,1.110,0.986,0.951,0.803,0.866,0.780
3,0.0,1.340,-0.877,0.936,1.990,0.882,1.790,-1.650,-9.42E-01,0.00,...,-0.6780,-1.360000,0.0,0.947,1.030,0.999,0.728,0.869,1.030,0.958
4,1.0,1.110,0.321,1.520,0.883,-1.210,0.681,-1.070,-9.22E-01,0.00,...,-0.3740,0.113000,0.0,0.756,1.360,0.987,0.838,1.130,0.872,0.808
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,0.0,0.680,0.223,-0.757,0.418,-0.323,0.471,-0.394,1.03E-01,0.00,...,-2.4600,1.460000,0.0,0.823,1.040,0.985,0.868,0.258,0.776,0.712
599996,1.0,1.610,-1.620,0.212,0.716,-0.906,0.553,-0.908,-1.56E+00,2.17,...,0.5380,-0.490000,3.10E+00,0.810,0.643,1.260,1.020,0.626,0.773,0.701
599997,1.0,1.070,0.364,0.344,0.617,-1.430,0.675,0.159,7.89E-02,0.00,...,0.9780,1.150000,3.10E+00,0.973,0.974,1.130,0.969,0.852,0.908,0.789
599998,1.0,1.180,-0.173,-1.460,0.735,-0.753,1.020,-0.838,1.23E+00,0.00,...,0.1070,0.622000,0.0,0.812,1.240,0.986,0.694,0.745,0.741,0.728
599999,0.0,0.771,-0.133,-1.020,1.790,-1.650,0.779,0.487,1.90E-01,2.17,...,-0.3140,0.667000,0.0,0.829,0.839,0.984,1.340,0.510,1.040,0.905